package com.fyp.virtualtryon.data.db

import android.content.Context
import com.fyp.virtualtryon.data.model.BodyType
import com.fyp.virtualtryon.data.model.Garment
import com.fyp.virtualtryon.data.model.GarmentGender
import com.fyp.virtualtryon.data.model.GarmentType
import org.json.JSONArray
import org.json.JSONObject

/**
 * Reads garments_catalog.json from assets/ and returns a list of [Garment] entities
 * ready to insert into Room. Called once from [AppDatabase] on first creation.
 *
 * The JSON is generated by scripts/prepare_dataset.py.
 */
object DatabaseSeeder {

    fun loadGarments(context: Context): List<Garment> {
        val json = try {
            context.assets.open("garments_catalog.json")
                .bufferedReader()
                .use { it.readText() }
        } catch (e: Exception) {
            e.printStackTrace()
            return emptyList()
        }

        val array   = JSONArray(json)
        val garments = mutableListOf<Garment>()

        for (i in 0 until array.length()) {
            val obj = array.getJSONObject(i)
            runCatching { parseGarment(obj) }
                .onSuccess { garments += it }
                .onFailure { e -> e.printStackTrace() }
        }

        return garments
    }

    private fun parseGarment(obj: JSONObject): Garment = Garment(
        name              = obj.getString("name"),
        type              = GarmentType.valueOf(obj.getString("type")),
        gender            = GarmentGender.valueOf(obj.getString("gender")),
        color             = obj.getString("color"),
        imageAssetPath    = obj.getString("imageAssetPath"),
        widthCm           = obj.getDouble("widthCm").toFloat(),
        heightCm          = obj.getDouble("heightCm").toFloat(),
        sizeLabel         = obj.getString("sizeLabel"),
        suitableBodyTypes = obj.getString("suitableBodyTypes"),
        suitableGenders   = obj.getString("suitableGenders"),
    )
}
